### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by thedrow** [rackerlabs/blueflood#437]
Documentation is the most important feature in an open source project.
It's impossible to use this as it is.

**Comment by stanzikratel** [comment]
@thedrow Please let us know your feedback. I've been working with the team on updating the docs and would be happy to incorporate any feedback you have

**Comment by thedrow** [comment]
The documentation is pretty much empty https://github.com/rackerlabs/blueflood/wiki/Query
https://github.com/rackerlabs/blueflood/wiki/Ingestion

**Comment by stanzikratel** [comment]
We have released documentation for the Rackspace-specific version of Blueflood, called Cloud Metrics. This may help you: http://docs.rackspace.com/cmet/api/v1.0/cmet-gettingstarted/content/doc-change-history.html
http://docs.rackspace.com/cmet/api/v1.0/cmet-devguide/content/Overview.html

Please feel free to send me any feedback about these docs

**Comment by meker12** [comment]
Cloud Metrics docs have moved here:  https://developer.rackspace.com/docs/metrics/v2/developer-guide/

If you have questions or issues, click "Submit an issue" in the navigation bar to submit them.
