### ISSUE TITLE
Request: Graphite backend

### ISSUE THREAD

**Issue by nicholaskuechler** [rackerlabs/blueflood#441]
I see there's a statsd backend which is awesome. Requesting a graphite backend so that I can set my carbon-relay to stream metrics to bluefood in the same way we can stream to blueflood-statsd.

Would really allow us (and I'm sure many others) to hook in to blueflood much easier.

We have too many metrics going to graphite (not via statsd) right now that switching to blueflood is going to be super difficult and time consuming. A graphite backend would make this process much easier to get started, allowing us to slowly convert everything else in the future, while still getting the immediate benefits.

**Comment by stackedsax** [comment]
Hey Nick,

I know you already know this, but we have a carbon-relay that we're working on:

https://github.com/rackerlabs/graphite-http-wrapper

It will be single-tenant at the moment, but should be a good way for people who already employ graphite to simply push their data into Blueflood.

**Comment by nicholaskuechler** [comment]
Following up: We've tested the graphite-http-wrapper and it works great!

Our graphite node is relaying metrics to a graphite-http-wrapper node, which then injects them in to blueflood. We can then see our metrics in blueflood via grafana. Everything's working very well for our needs. Thanks so much!

From my perspective, I think we can close out this issue, unless you still need it open on your side?

**Comment by stackedsax** [comment]
Sounds great!  I'll close this issue for now.
