### ISSUE TITLE
JSON parser fails on single items.

### ISSUE THREAD

**Issue by creationix** [rackerlabs/blueflood#638]
If I send the following sample data to blueflood, it works fine:

```json
[{
  "collectionTime": 1450830038000,
  "ttlInSeconds": 172800,
  "metricValue": 66,
  "metricName": "example.metric.one"
},{
  "tenantId": "540561",
  "collectionTime": 1376509892612,
  "ttlInSeconds": 172800,
  "metricValue": 66,
  "metricName": "example.metric.two"
}]
```

But if I send a single item, it fails with a `400` response saying `Cannot parse content`.

```json
[{
  "collectionTime": 1450830038000,
  "ttlInSeconds": 172800,
  "metricValue": 66,
  "metricName": "example.metric.one"
}]
```

If I add a trailing comma after the first item, it succeeds.  

```json
[{
  "collectionTime": 1450830038000,
  "ttlInSeconds": 172800,
  "metricValue": 66,
  "metricName": "example.metric.one"
},]
```

This is not an acceptable workaround since this is invalid JSON and I would have to manually construct the string instead of using normal JSON encoding libraries.

**Comment by creationix** [comment]
Hold on a second.  I'm not 100% sure this is the problem.  We're getting inconsistent results in further testing.  Will report back if the problem is indeed on blueflood side.

**Comment by creationix** [comment]
So this was a series of several problems and multiple mistakes all having the exact same symptoms.

While not required, it would be really nice if the JSON parser would give a more meaningful error message when it fails.  We had everything from stray text to unexpected fields to wrong endpoint urls to invalid content-type and content-encoding headers all with the exact same 400 and `Cannot parse content`.  This was especially frustrating when we used wireshark to verify out request was properly formed and had valid JSON, but still got the parse error response. (In this last case we were sending `tenantId`, but were using the non-multi endpoint.  A parse error message led us astray from the real problem)

**Comment by shintasmith** [comment]
Hi @creationix , as it turns out, we did create a story to better handle validation. We will probably tackle it next sprint. Thanks!

**Comment by creationix** [comment]
Awesome!
