### ISSUE TITLE
CQL Version mismatch in docker

### ISSUE THREAD

**Issue by timothyarnold1983** [rackerlabs/blueflood#668]
Good afternoon
(I'm not an expert in well, anything so apologies for the terminology)

Ive just deployed a new test installation in docker following the 10 minute guide and everything started, however a 500 Error when attempting to insert data.

Looking through it appears that the "keyspace data" didn't exist. Logging into the cassandra servers and found that the keyspace didn't exist.

Tried to load the blueflood.cdl file found that there is a version mismatch between the cqlsh and the cassandra servers. forcing the load using:

cqlsh 172.17.0.2 -f blueflood.cdl --cqlversion=3.2.1

that works, and I now have data...

Thanks
Tim

**Comment by shintasmith** [comment]
Hi, @timothyarnold1983, 
Thanks for bringing this up to us. We will look into it and either fix the documentation or the docker image.

Thanks,
-shinta

**Comment by goru97** [comment]
@timothyarnold1983 This issue is fixed in https://github.com/rackerlabs/blueflood/pull/695
