### ISSUE TITLE
Is the data in metrics_state correct?

### ISSUE THREAD

**Issue by 42701618** [rackerlabs/blueflood#773]
select * FROM "DATA".metrics_state  where key=111;

 key | column1           | value
-----+-------------------+---------------
 111 | metrics_1440m,7,A | 1483617238069
 111 | metrics_20m,539,A | 1483617238069
 111 | metrics_240m,44,A | 1483617238069
 111 | metrics_5m,2156,A | 1483616699998
 111 | metrics_5m,2156,X | 1483616699998
 111 | metrics_5m,2157,A | 1483616999534
 111 | metrics_5m,2158,A | 1483617238069
 111 | metrics_60m,179,A | 1483617238069
(8 rows)

After some minute,

select * FROM "DATA".metrics_state  where key=111;

 key | column1           | value
-----+-------------------+---------------
 111 | metrics_1440m,7,A | 1483617366021
 111 | metrics_20m,539,A | 1483617366021
 111 | metrics_240m,44,A | 1483617366021
 111 | metrics_5m,2156,A | 1483616699998
 111 | metrics_5m,2156,X | 1483616699998
 111 | metrics_5m,2157,A | 1483616999534
 111 | metrics_5m,2157,X | 1483616999534
 111 | metrics_5m,2158,A | 1483617299967
 111 | metrics_5m,2159,A | 1483617366021
 111 | metrics_60m,179,A | 1483617366021

(10 rows)

I find that "metrics_5m,2156,A" and  "metrics_5m,2156,X" are in the table at the same time.Is it normal?
My code‘s version is v1.0.1956

**Comment by ChandraAddala** [comment]
Yes its normal. If they are same, its an indication that the rollup finished for that slot 2156 and that timestamp is the `collectoinTime` of the last ingested metric corresponding to that slot.

**Comment by 42701618** [comment]
thx
