### ISSUE TITLE
Health/Status ingest endpoint

### ISSUE THREAD

**Issue by jtlisi** [rackerlabs/blueflood#778]
Blueflood doesn't seem to have a good endpoint that ensures it's services are running correctly. Would it be possible to add a healthcheck endpoint to blueflood that returns a 200 and tells which services are active?

**Comment by usnavi** [comment]
Hi @jtlisi - At Rackspace, we currently do a GET on the  ```/v2.0``` endpoint to detect if the server is up on the particular node.  You could do that across your ingest and query nodes as a temporary solution.  Currently, blueflood doesn't communicate status across nodes, so that would need to be added.

**Comment by sriharshasingudasu** [comment]
Hi @usnavi. I would like to help with Health check end point if there is something in the road map. It will be like a minor add on.

**Comment by usnavi** [comment]
@ssing6 - sounds great!  Let's talk detail.  What would be the format of the data returned?  You have an example response?

**Comment by ssing6** [comment]
@usnavi This will an optional usage. Like for teams who need a health end point.

When we start the app, in reality app is in running mode. But health says app is down. It is responsibility of the team to change the health status.

Details of change:
- It will be an extra end point "/health" for both Ingest and Query.
[HttpMetricsIngestionServer and HttpMetricDataQueryServer with a new "HealthCheckHandler" class]
- We can set some headers if required like an HealthKey. 

Output:
curl -H "HealthKey:@3lkaJJanj" -X POST "http://bfmachine:port/health"
Response will be 200 if HealthKey is passed or 401 and there is obviously 503.
