### ISSUE TITLE
Exception in thread "Excess Enum Table Reader" java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by 42701618** [rackerlabs/blueflood#800]
Hi team,
When I start the blueflood,the log will show "Exception in thread "Excess Enum Table Reader" java.lang.OutOfMemoryError: unable to create new native thread"

I have tried to modify -Xms，-Xmx，-Xss,and
proc/sys/kernel/pid_max，
/proc/sys/kernel/thread-max，
max_user_process（ulimit -u），
/proc/sys/vm/max_map_count。

but the error  still exist.

thanks

**Comment by ChandraAddala** [comment]
We removed that thread, as we removed support for enums recently. If you pick the latest, you should not see that error.

**Comment by 42701618** [comment]
thanks
